# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='email',
            new_name='username',
        ),
    ]
