# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20170728_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='username',
            new_name='email',
        ),
    ]
