# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20170728_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
